stages:
  - verify
  - publish

default:
  image: $NEBULA_CI_IMAGE
  tags:
    - $NEBULA_RUNNER_TAG
  cache:
    key: maven-$CI_PROJECT_ID
    paths:
      - .m2/repository/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

verify:
  stage: verify
  script:
    - >
      mvn --settings "$MAVEN_VERIFY_SETTINGS_XML"
      -B
      -U
      -fae
      -Dmaven.wagon.http.pool=false
      -Dmaven.wagon.http.retryHandler.count=5
      -Dmaven.wagon.rto=60000
      -pl '!examples'
      verify
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'

publish:
  stage: publish
  script:
    - >
      mvn --settings "$MAVEN_DEPLOY_SETTINGS_XML"
      -B
      -U
      -fae
      -DdeployAtEnd=true
      -Dmaven.wagon.http.pool=false
      -Dmaven.wagon.http.retryHandler.count=5
      -Dmaven.wagon.rto=60000
      -pl '!examples'
      deploy
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
