# nebula-starter-service defaults
nebula.data.persistence.enabled=true
nebula.data.cache.enabled=true
nebula.rpc.http.enabled=true
nebula.rpc.discovery.enabled=true
nebula.discovery.nacos.enabled=true
nebula.lock.enabled=true
