// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_common.proto

// Protobuf Java Version: 3.25.5
package io.nebula.rpc.grpc.proto;

public final class RpcCommonProto {
  private RpcCommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_nebula_rpc_grpc_RpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_nebula_rpc_grpc_RpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_nebula_rpc_grpc_RpcRequest_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_nebula_rpc_grpc_RpcRequest_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_nebula_rpc_grpc_RpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_nebula_rpc_grpc_RpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_nebula_rpc_grpc_RpcResponse_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_nebula_rpc_grpc_RpcResponse_MetadataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020rpc_common.proto\022\022io.nebula.rpc.grpc\"\374" +
      "\001\n\nRpcRequest\022\022\n\nrequest_id\030\001 \001(\t\022\024\n\014ser" +
      "vice_name\030\002 \001(\t\022\023\n\013method_name\030\003 \001(\t\022\027\n\017" +
      "parameter_types\030\004 \003(\t\022\022\n\nparameters\030\005 \003(" +
      "\t\022>\n\010metadata\030\006 \003(\0132,.io.nebula.rpc.grpc" +
      ".RpcRequest.MetadataEntry\022\021\n\ttimestamp\030\007" +
      " \001(\003\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001\"\207\002\n\013RpcResponse\022\022\n\nrequest" +
      "_id\030\001 \001(\t\022\017\n\007success\030\002 \001(\010\022\016\n\006result\030\003 \001" +
      "(\t\022\022\n\nerror_code\030\004 \001(\t\022\025\n\rerror_message\030" +
      "\005 \001(\t\022\023\n\013stack_trace\030\006 \001(\t\022?\n\010metadata\030\007" +
      " \003(\0132-.io.nebula.rpc.grpc.RpcResponse.Me" +
      "tadataEntry\022\021\n\ttimestamp\030\010 \001(\003\032/\n\rMetada" +
      "taEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012" +
      "\336\002\n\021GenericRpcService\022G\n\004Call\022\036.io.nebul" +
      "a.rpc.grpc.RpcRequest\032\037.io.nebula.rpc.gr" +
      "pc.RpcResponse\022Q\n\014ServerStream\022\036.io.nebu" +
      "la.rpc.grpc.RpcRequest\032\037.io.nebula.rpc.g" +
      "rpc.RpcResponse0\001\022Q\n\014ClientStream\022\036.io.n" +
      "ebula.rpc.grpc.RpcRequest\032\037.io.nebula.rp" +
      "c.grpc.RpcResponse(\001\022Z\n\023BidirectionalStr" +
      "eam\022\036.io.nebula.rpc.grpc.RpcRequest\032\037.io" +
      ".nebula.rpc.grpc.RpcResponse(\0010\001B,\n\030io.n" +
      "ebula.rpc.grpc.protoB\016RpcCommonProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_nebula_rpc_grpc_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_nebula_rpc_grpc_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_nebula_rpc_grpc_RpcRequest_descriptor,
        new java.lang.String[] { "RequestId", "ServiceName", "MethodName", "ParameterTypes", "Parameters", "Metadata", "Timestamp", });
    internal_static_io_nebula_rpc_grpc_RpcRequest_MetadataEntry_descriptor =
      internal_static_io_nebula_rpc_grpc_RpcRequest_descriptor.getNestedTypes().get(0);
    internal_static_io_nebula_rpc_grpc_RpcRequest_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_nebula_rpc_grpc_RpcRequest_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_nebula_rpc_grpc_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_nebula_rpc_grpc_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_nebula_rpc_grpc_RpcResponse_descriptor,
        new java.lang.String[] { "RequestId", "Success", "Result", "ErrorCode", "ErrorMessage", "StackTrace", "Metadata", "Timestamp", });
    internal_static_io_nebula_rpc_grpc_RpcResponse_MetadataEntry_descriptor =
      internal_static_io_nebula_rpc_grpc_RpcResponse_descriptor.getNestedTypes().get(0);
    internal_static_io_nebula_rpc_grpc_RpcResponse_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_nebula_rpc_grpc_RpcResponse_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
