// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_common.proto

// Protobuf Java Version: 3.25.5
package io.nebula.rpc.grpc.proto;

public interface RpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.nebula.rpc.grpc.RpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 请求ID
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * 请求ID
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * 服务接口名
   * </pre>
   *
   * <code>string service_name = 2;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <pre>
   * 服务接口名
   * </pre>
   *
   * <code>string service_name = 2;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <pre>
   * 方法名
   * </pre>
   *
   * <code>string method_name = 3;</code>
   * @return The methodName.
   */
  java.lang.String getMethodName();
  /**
   * <pre>
   * 方法名
   * </pre>
   *
   * <code>string method_name = 3;</code>
   * @return The bytes for methodName.
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <pre>
   * 参数类型列表(全限定类名)
   * </pre>
   *
   * <code>repeated string parameter_types = 4;</code>
   * @return A list containing the parameterTypes.
   */
  java.util.List<java.lang.String>
      getParameterTypesList();
  /**
   * <pre>
   * 参数类型列表(全限定类名)
   * </pre>
   *
   * <code>repeated string parameter_types = 4;</code>
   * @return The count of parameterTypes.
   */
  int getParameterTypesCount();
  /**
   * <pre>
   * 参数类型列表(全限定类名)
   * </pre>
   *
   * <code>repeated string parameter_types = 4;</code>
   * @param index The index of the element to return.
   * @return The parameterTypes at the given index.
   */
  java.lang.String getParameterTypes(int index);
  /**
   * <pre>
   * 参数类型列表(全限定类名)
   * </pre>
   *
   * <code>repeated string parameter_types = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the parameterTypes at the given index.
   */
  com.google.protobuf.ByteString
      getParameterTypesBytes(int index);

  /**
   * <pre>
   * 参数值(JSON序列化)
   * </pre>
   *
   * <code>repeated string parameters = 5;</code>
   * @return A list containing the parameters.
   */
  java.util.List<java.lang.String>
      getParametersList();
  /**
   * <pre>
   * 参数值(JSON序列化)
   * </pre>
   *
   * <code>repeated string parameters = 5;</code>
   * @return The count of parameters.
   */
  int getParametersCount();
  /**
   * <pre>
   * 参数值(JSON序列化)
   * </pre>
   *
   * <code>repeated string parameters = 5;</code>
   * @param index The index of the element to return.
   * @return The parameters at the given index.
   */
  java.lang.String getParameters(int index);
  /**
   * <pre>
   * 参数值(JSON序列化)
   * </pre>
   *
   * <code>repeated string parameters = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the parameters at the given index.
   */
  com.google.protobuf.ByteString
      getParametersBytes(int index);

  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  int getMetadataCount();
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  boolean containsMetadata(
      java.lang.String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetadata();
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetadataMap();
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  java.lang.String getMetadataOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
