// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_common.proto

// Protobuf Java Version: 3.25.5
package io.nebula.rpc.grpc.proto;

/**
 * <pre>
 * 通用RPC请求消息
 * </pre>
 *
 * Protobuf type {@code io.nebula.rpc.grpc.RpcRequest}
 */
public final class RpcRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.nebula.rpc.grpc.RpcRequest)
    RpcRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RpcRequest.newBuilder() to construct.
  private RpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RpcRequest() {
    requestId_ = "";
    serviceName_ = "";
    methodName_ = "";
    parameterTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    parameters_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RpcRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.nebula.rpc.grpc.proto.RpcCommonProto.internal_static_io_nebula_rpc_grpc_RpcRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 6:
        return internalGetMetadata();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.nebula.rpc.grpc.proto.RpcCommonProto.internal_static_io_nebula_rpc_grpc_RpcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.nebula.rpc.grpc.proto.RpcRequest.class, io.nebula.rpc.grpc.proto.RpcRequest.Builder.class);
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object requestId_ = "";
  /**
   * <pre>
   * 请求ID
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 请求ID
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICE_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serviceName_ = "";
  /**
   * <pre>
   * 服务接口名
   * </pre>
   *
   * <code>string service_name = 2;</code>
   * @return The serviceName.
   */
  @java.lang.Override
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 服务接口名
   * </pre>
   *
   * <code>string service_name = 2;</code>
   * @return The bytes for serviceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHOD_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object methodName_ = "";
  /**
   * <pre>
   * 方法名
   * </pre>
   *
   * <code>string method_name = 3;</code>
   * @return The methodName.
   */
  @java.lang.Override
  public java.lang.String getMethodName() {
    java.lang.Object ref = methodName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      methodName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 方法名
   * </pre>
   *
   * <code>string method_name = 3;</code>
   * @return The bytes for methodName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMethodNameBytes() {
    java.lang.Object ref = methodName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      methodName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMETER_TYPES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList parameterTypes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 参数类型列表(全限定类名)
   * </pre>
   *
   * <code>repeated string parameter_types = 4;</code>
   * @return A list containing the parameterTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getParameterTypesList() {
    return parameterTypes_;
  }
  /**
   * <pre>
   * 参数类型列表(全限定类名)
   * </pre>
   *
   * <code>repeated string parameter_types = 4;</code>
   * @return The count of parameterTypes.
   */
  public int getParameterTypesCount() {
    return parameterTypes_.size();
  }
  /**
   * <pre>
   * 参数类型列表(全限定类名)
   * </pre>
   *
   * <code>repeated string parameter_types = 4;</code>
   * @param index The index of the element to return.
   * @return The parameterTypes at the given index.
   */
  public java.lang.String getParameterTypes(int index) {
    return parameterTypes_.get(index);
  }
  /**
   * <pre>
   * 参数类型列表(全限定类名)
   * </pre>
   *
   * <code>repeated string parameter_types = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the parameterTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getParameterTypesBytes(int index) {
    return parameterTypes_.getByteString(index);
  }

  public static final int PARAMETERS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList parameters_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 参数值(JSON序列化)
   * </pre>
   *
   * <code>repeated string parameters = 5;</code>
   * @return A list containing the parameters.
   */
  public com.google.protobuf.ProtocolStringList
      getParametersList() {
    return parameters_;
  }
  /**
   * <pre>
   * 参数值(JSON序列化)
   * </pre>
   *
   * <code>repeated string parameters = 5;</code>
   * @return The count of parameters.
   */
  public int getParametersCount() {
    return parameters_.size();
  }
  /**
   * <pre>
   * 参数值(JSON序列化)
   * </pre>
   *
   * <code>repeated string parameters = 5;</code>
   * @param index The index of the element to return.
   * @return The parameters at the given index.
   */
  public java.lang.String getParameters(int index) {
    return parameters_.get(index);
  }
  /**
   * <pre>
   * 参数值(JSON序列化)
   * </pre>
   *
   * <code>repeated string parameters = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the parameters at the given index.
   */
  public com.google.protobuf.ByteString
      getParametersBytes(int index) {
    return parameters_.getByteString(index);
  }

  public static final int METADATA_FIELD_NUMBER = 6;
  private static final class MetadataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                io.nebula.rpc.grpc.proto.RpcCommonProto.internal_static_io_nebula_rpc_grpc_RpcRequest_MetadataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> metadata_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMetadata() {
    if (metadata_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetadataDefaultEntryHolder.defaultEntry);
    }
    return metadata_;
  }
  public int getMetadataCount() {
    return internalGetMetadata().getMap().size();
  }
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  @java.lang.Override
  public boolean containsMetadata(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMetadata().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
    return getMetadataMap();
  }
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
    return internalGetMetadata().getMap();
  }
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetadata().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  @java.lang.Override
  public java.lang.String getMetadataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetadata().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, methodName_);
    }
    for (int i = 0; i < parameterTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parameterTypes_.getRaw(i));
    }
    for (int i = 0; i < parameters_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, parameters_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMetadata(),
        MetadataDefaultEntryHolder.defaultEntry,
        6);
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, methodName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < parameterTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(parameterTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getParameterTypesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < parameters_.size(); i++) {
        dataSize += computeStringSizeNoTag(parameters_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getParametersList().size();
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMetadata().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, metadata__);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.nebula.rpc.grpc.proto.RpcRequest)) {
      return super.equals(obj);
    }
    io.nebula.rpc.grpc.proto.RpcRequest other = (io.nebula.rpc.grpc.proto.RpcRequest) obj;

    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (!getServiceName()
        .equals(other.getServiceName())) return false;
    if (!getMethodName()
        .equals(other.getMethodName())) return false;
    if (!getParameterTypesList()
        .equals(other.getParameterTypesList())) return false;
    if (!getParametersList()
        .equals(other.getParametersList())) return false;
    if (!internalGetMetadata().equals(
        other.internalGetMetadata())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMethodName().hashCode();
    if (getParameterTypesCount() > 0) {
      hash = (37 * hash) + PARAMETER_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getParameterTypesList().hashCode();
    }
    if (getParametersCount() > 0) {
      hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getParametersList().hashCode();
    }
    if (!internalGetMetadata().getMap().isEmpty()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetadata().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.nebula.rpc.grpc.proto.RpcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nebula.rpc.grpc.proto.RpcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nebula.rpc.grpc.proto.RpcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nebula.rpc.grpc.proto.RpcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nebula.rpc.grpc.proto.RpcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nebula.rpc.grpc.proto.RpcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nebula.rpc.grpc.proto.RpcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nebula.rpc.grpc.proto.RpcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.nebula.rpc.grpc.proto.RpcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.nebula.rpc.grpc.proto.RpcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nebula.rpc.grpc.proto.RpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nebula.rpc.grpc.proto.RpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.nebula.rpc.grpc.proto.RpcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 通用RPC请求消息
   * </pre>
   *
   * Protobuf type {@code io.nebula.rpc.grpc.RpcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.nebula.rpc.grpc.RpcRequest)
      io.nebula.rpc.grpc.proto.RpcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.nebula.rpc.grpc.proto.RpcCommonProto.internal_static_io_nebula_rpc_grpc_RpcRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 6:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.nebula.rpc.grpc.proto.RpcCommonProto.internal_static_io_nebula_rpc_grpc_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.nebula.rpc.grpc.proto.RpcRequest.class, io.nebula.rpc.grpc.proto.RpcRequest.Builder.class);
    }

    // Construct using io.nebula.rpc.grpc.proto.RpcRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requestId_ = "";
      serviceName_ = "";
      methodName_ = "";
      parameterTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      parameters_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      internalGetMutableMetadata().clear();
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.nebula.rpc.grpc.proto.RpcCommonProto.internal_static_io_nebula_rpc_grpc_RpcRequest_descriptor;
    }

    @java.lang.Override
    public io.nebula.rpc.grpc.proto.RpcRequest getDefaultInstanceForType() {
      return io.nebula.rpc.grpc.proto.RpcRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.nebula.rpc.grpc.proto.RpcRequest build() {
      io.nebula.rpc.grpc.proto.RpcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.nebula.rpc.grpc.proto.RpcRequest buildPartial() {
      io.nebula.rpc.grpc.proto.RpcRequest result = new io.nebula.rpc.grpc.proto.RpcRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.nebula.rpc.grpc.proto.RpcRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestId_ = requestId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.serviceName_ = serviceName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.methodName_ = methodName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        parameterTypes_.makeImmutable();
        result.parameterTypes_ = parameterTypes_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        parameters_.makeImmutable();
        result.parameters_ = parameters_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.metadata_ = internalGetMetadata();
        result.metadata_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.nebula.rpc.grpc.proto.RpcRequest) {
        return mergeFrom((io.nebula.rpc.grpc.proto.RpcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.nebula.rpc.grpc.proto.RpcRequest other) {
      if (other == io.nebula.rpc.grpc.proto.RpcRequest.getDefaultInstance()) return this;
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getMethodName().isEmpty()) {
        methodName_ = other.methodName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.parameterTypes_.isEmpty()) {
        if (parameterTypes_.isEmpty()) {
          parameterTypes_ = other.parameterTypes_;
          bitField0_ |= 0x00000008;
        } else {
          ensureParameterTypesIsMutable();
          parameterTypes_.addAll(other.parameterTypes_);
        }
        onChanged();
      }
      if (!other.parameters_.isEmpty()) {
        if (parameters_.isEmpty()) {
          parameters_ = other.parameters_;
          bitField0_ |= 0x00000010;
        } else {
          ensureParametersIsMutable();
          parameters_.addAll(other.parameters_);
        }
        onChanged();
      }
      internalGetMutableMetadata().mergeFrom(
          other.internalGetMetadata());
      bitField0_ |= 0x00000020;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              requestId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              serviceName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              methodName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureParameterTypesIsMutable();
              parameterTypes_.add(s);
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureParametersIsMutable();
              parameters_.add(s);
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metadata__ = input.readMessage(
                  MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMetadata().getMutableMap().put(
                  metadata__.getKey(), metadata__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object requestId_ = "";
    /**
     * <pre>
     * 请求ID
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 请求ID
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 请求ID
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求ID
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      requestId_ = getDefaultInstance().getRequestId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求ID
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object serviceName_ = "";
    /**
     * <pre>
     * 服务接口名
     * </pre>
     *
     * <code>string service_name = 2;</code>
     * @return The serviceName.
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 服务接口名
     * </pre>
     *
     * <code>string service_name = 2;</code>
     * @return The bytes for serviceName.
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 服务接口名
     * </pre>
     *
     * <code>string service_name = 2;</code>
     * @param value The serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serviceName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 服务接口名
     * </pre>
     *
     * <code>string service_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceName() {
      serviceName_ = getDefaultInstance().getServiceName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 服务接口名
     * </pre>
     *
     * <code>string service_name = 2;</code>
     * @param value The bytes for serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serviceName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object methodName_ = "";
    /**
     * <pre>
     * 方法名
     * </pre>
     *
     * <code>string method_name = 3;</code>
     * @return The methodName.
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 方法名
     * </pre>
     *
     * <code>string method_name = 3;</code>
     * @return The bytes for methodName.
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 方法名
     * </pre>
     *
     * <code>string method_name = 3;</code>
     * @param value The methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      methodName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 方法名
     * </pre>
     *
     * <code>string method_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethodName() {
      methodName_ = getDefaultInstance().getMethodName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 方法名
     * </pre>
     *
     * <code>string method_name = 3;</code>
     * @param value The bytes for methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      methodName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList parameterTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureParameterTypesIsMutable() {
      if (!parameterTypes_.isModifiable()) {
        parameterTypes_ = new com.google.protobuf.LazyStringArrayList(parameterTypes_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * 参数类型列表(全限定类名)
     * </pre>
     *
     * <code>repeated string parameter_types = 4;</code>
     * @return A list containing the parameterTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParameterTypesList() {
      parameterTypes_.makeImmutable();
      return parameterTypes_;
    }
    /**
     * <pre>
     * 参数类型列表(全限定类名)
     * </pre>
     *
     * <code>repeated string parameter_types = 4;</code>
     * @return The count of parameterTypes.
     */
    public int getParameterTypesCount() {
      return parameterTypes_.size();
    }
    /**
     * <pre>
     * 参数类型列表(全限定类名)
     * </pre>
     *
     * <code>repeated string parameter_types = 4;</code>
     * @param index The index of the element to return.
     * @return The parameterTypes at the given index.
     */
    public java.lang.String getParameterTypes(int index) {
      return parameterTypes_.get(index);
    }
    /**
     * <pre>
     * 参数类型列表(全限定类名)
     * </pre>
     *
     * <code>repeated string parameter_types = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameterTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParameterTypesBytes(int index) {
      return parameterTypes_.getByteString(index);
    }
    /**
     * <pre>
     * 参数类型列表(全限定类名)
     * </pre>
     *
     * <code>repeated string parameter_types = 4;</code>
     * @param index The index to set the value at.
     * @param value The parameterTypes to set.
     * @return This builder for chaining.
     */
    public Builder setParameterTypes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParameterTypesIsMutable();
      parameterTypes_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参数类型列表(全限定类名)
     * </pre>
     *
     * <code>repeated string parameter_types = 4;</code>
     * @param value The parameterTypes to add.
     * @return This builder for chaining.
     */
    public Builder addParameterTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParameterTypesIsMutable();
      parameterTypes_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参数类型列表(全限定类名)
     * </pre>
     *
     * <code>repeated string parameter_types = 4;</code>
     * @param values The parameterTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllParameterTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureParameterTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, parameterTypes_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参数类型列表(全限定类名)
     * </pre>
     *
     * <code>repeated string parameter_types = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearParameterTypes() {
      parameterTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参数类型列表(全限定类名)
     * </pre>
     *
     * <code>repeated string parameter_types = 4;</code>
     * @param value The bytes of the parameterTypes to add.
     * @return This builder for chaining.
     */
    public Builder addParameterTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureParameterTypesIsMutable();
      parameterTypes_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList parameters_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureParametersIsMutable() {
      if (!parameters_.isModifiable()) {
        parameters_ = new com.google.protobuf.LazyStringArrayList(parameters_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * 参数值(JSON序列化)
     * </pre>
     *
     * <code>repeated string parameters = 5;</code>
     * @return A list containing the parameters.
     */
    public com.google.protobuf.ProtocolStringList
        getParametersList() {
      parameters_.makeImmutable();
      return parameters_;
    }
    /**
     * <pre>
     * 参数值(JSON序列化)
     * </pre>
     *
     * <code>repeated string parameters = 5;</code>
     * @return The count of parameters.
     */
    public int getParametersCount() {
      return parameters_.size();
    }
    /**
     * <pre>
     * 参数值(JSON序列化)
     * </pre>
     *
     * <code>repeated string parameters = 5;</code>
     * @param index The index of the element to return.
     * @return The parameters at the given index.
     */
    public java.lang.String getParameters(int index) {
      return parameters_.get(index);
    }
    /**
     * <pre>
     * 参数值(JSON序列化)
     * </pre>
     *
     * <code>repeated string parameters = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameters at the given index.
     */
    public com.google.protobuf.ByteString
        getParametersBytes(int index) {
      return parameters_.getByteString(index);
    }
    /**
     * <pre>
     * 参数值(JSON序列化)
     * </pre>
     *
     * <code>repeated string parameters = 5;</code>
     * @param index The index to set the value at.
     * @param value The parameters to set.
     * @return This builder for chaining.
     */
    public Builder setParameters(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParametersIsMutable();
      parameters_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参数值(JSON序列化)
     * </pre>
     *
     * <code>repeated string parameters = 5;</code>
     * @param value The parameters to add.
     * @return This builder for chaining.
     */
    public Builder addParameters(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParametersIsMutable();
      parameters_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参数值(JSON序列化)
     * </pre>
     *
     * <code>repeated string parameters = 5;</code>
     * @param values The parameters to add.
     * @return This builder for chaining.
     */
    public Builder addAllParameters(
        java.lang.Iterable<java.lang.String> values) {
      ensureParametersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, parameters_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参数值(JSON序列化)
     * </pre>
     *
     * <code>repeated string parameters = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearParameters() {
      parameters_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参数值(JSON序列化)
     * </pre>
     *
     * <code>repeated string parameters = 5;</code>
     * @param value The bytes of the parameters to add.
     * @return This builder for chaining.
     */
    public Builder addParametersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureParametersIsMutable();
      parameters_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metadata_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableMetadata() {
      if (metadata_ == null) {
        metadata_ = com.google.protobuf.MapField.newMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      if (!metadata_.isMutable()) {
        metadata_ = metadata_.copy();
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return metadata_;
    }
    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    @java.lang.Override
    public boolean containsMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetadataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    @java.lang.Override
    public java.lang.String getMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableMetadata().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    public Builder removeMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMetadata().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableMetadata() {
      bitField0_ |= 0x00000020;
      return internalGetMutableMetadata().getMutableMap();
    }
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    public Builder putMetadata(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMetadata().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    public Builder putAllMetadata(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMetadata().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.nebula.rpc.grpc.RpcRequest)
  }

  // @@protoc_insertion_point(class_scope:io.nebula.rpc.grpc.RpcRequest)
  private static final io.nebula.rpc.grpc.proto.RpcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.nebula.rpc.grpc.proto.RpcRequest();
  }

  public static io.nebula.rpc.grpc.proto.RpcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcRequest>
      PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
    @java.lang.Override
    public RpcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RpcRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.nebula.rpc.grpc.proto.RpcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

