// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_common.proto

// Protobuf Java Version: 3.25.5
package io.nebula.rpc.grpc.proto;

public interface RpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.nebula.rpc.grpc.RpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 请求ID(对应请求)
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * 请求ID(对应请求)
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * 是否成功
   * </pre>
   *
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   * 返回值(JSON序列化)
   * </pre>
   *
   * <code>string result = 3;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <pre>
   * 返回值(JSON序列化)
   * </pre>
   *
   * <code>string result = 3;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <pre>
   * 错误码
   * </pre>
   *
   * <code>string error_code = 4;</code>
   * @return The errorCode.
   */
  java.lang.String getErrorCode();
  /**
   * <pre>
   * 错误码
   * </pre>
   *
   * <code>string error_code = 4;</code>
   * @return The bytes for errorCode.
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();

  /**
   * <pre>
   * 错误消息
   * </pre>
   *
   * <code>string error_message = 5;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <pre>
   * 错误消息
   * </pre>
   *
   * <code>string error_message = 5;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * 异常堆栈
   * </pre>
   *
   * <code>string stack_trace = 6;</code>
   * @return The stackTrace.
   */
  java.lang.String getStackTrace();
  /**
   * <pre>
   * 异常堆栈
   * </pre>
   *
   * <code>string stack_trace = 6;</code>
   * @return The bytes for stackTrace.
   */
  com.google.protobuf.ByteString
      getStackTraceBytes();

  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 7;</code>
   */
  int getMetadataCount();
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 7;</code>
   */
  boolean containsMetadata(
      java.lang.String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetadata();
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 7;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetadataMap();
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 7;</code>
   */
  /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 元数据
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 7;</code>
   */
  java.lang.String getMetadataOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int64 timestamp = 8;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
